---
title: "pdf_extract"
format: html
editor: visual
---

```{r}
#install.packages("pdftools") 
require(pdftools)           
setwd("~/Downloads/bst260-final/code")
```

```{r}
pdf_text_data <- pdf_text("./../data/Mortalidad-RegDem-2015-17-NYT-part1.pdf")
pdf_text_data
```

```{r}
#View line wise for one page
strsplit(pdf_text_data[1], "\n")[[1]]
```

```{r}
#Data of interest starts on line 5
strsplit(pdf_text_data[1], "\n")[[1]][5]
```

```{r}
strsplit(strsplit(pdf_text_data[1], "\n")[[1]][5]," ")
##Num spaces between integers -> 4,7,3,3
#This remains consistent throughout for single digits. For double digits it
```

```{r}
#There are some lines with no data 
for (i in 5:36){
  print(strsplit(strsplit(pdf_text_data[1], "\n")[[1]][i]," "))
  print("--------")
}

```

```{r}
strsplit(strsplit(pdf_text_data[1], "\n")[[1]][5]," ")[[1]][5]
strsplit(strsplit(pdf_text_data[1], "\n")[[1]][5]," ")[[1]][13]
strsplit(strsplit(pdf_text_data[1], "\n")[[1]][5]," ")[[1]][17]
strsplit(strsplit(pdf_text_data[1], "\n")[[1]][5]," ")[[1]][21]

```

```{r}
for (j in 1:12) {
  f <- 0
  for (i in 4:100) {
    x <- strsplit(strsplit(pdf_text_data[j], "\n")[[1]][i]," ")[[1]]
    if(f==0 & is.na(as.integer(x[which(x!="")[1]]) )) {
      if(x[which(x!="")[1]]!="16-17") {
        month <- x[which(x!="")[1]]
        f <- 1
        print(month)
      }
    }
    if(f==1) {
      if(x[which(x!="")[1]]=='Total') {
        break
      }
      if(which(x!="")[1]>25 | is.na(as.integer(x[which(x!="")[1]]))) {
        next
      }
      date <- x[which(x!="")][1]
      y_2015 <- x[which(x!="")][2]
      y_2016 <- x[which(x!="")][3]
      y_2017 <- x[which(x!="")][4]
      print(paste(date, y_2015, y_2016,y_2017))
    }
  }
}
```

```{r}
df <- data.frame(date = integer(), month=character(), year = integer(), count = integer())
for (j in 1:12) {
  f <- 0
  for (i in 4:100) {
    x <- strsplit(strsplit(pdf_text_data[j], "\n")[[1]][i]," ")[[1]]
    if(f==0 & is.na(as.integer(x[which(x!="")[1]]) )) {
      if(x[which(x!="")[1]]!="16-17") {
        month <- x[which(x!="")[1]]
        f <- 1
        print(month)
      }
    }
    if(f==1) {
      if(x[which(x!="")[1]]=='Total') {
        break
      }
      if(which(x!="")[1]>25 | is.na(as.integer(x[which(x!="")[1]]))) {
        next
      }
      date <- x[which(x!="")][1]
      y_2015 <- x[which(x!="")][2]
      y_2016 <- x[which(x!="")][3]
      y_2017 <- x[which(x!="")][4]
      df <- rbind(df, data.frame(date = date, month = month, year = 2015, count = y_2015))
      df <- rbind(df, data.frame(date = date, month = month, year = 2016, count = y_2016))
      df <- rbind(df, data.frame(date = date, month = month, year = 2017, count = y_2017))
    }
  }
}
```

```{r}
df
```

```{r}
df <- df[!(df$month=='DEC'& df$year==2017),]
write.csv(df, "~/Downloads/excess_mort_.csv")
```
